[package]
name = "pumpkin-web-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pumpkin-core = "0.2"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"

[patch.crates-io]
pumpkin-core = { git = "https://github.com/geraschenko/Pumpkin" }
